config/routes.rb
Rails.application.routes.draw do
  get  '/search',  to: 'shops#search'
  get  '/postlist/:id',  to: 'shops#postlist', as: 'postlist'
  get  '/postlist_member/:id',  to: 'members#postlist_member', as: 'postlist_member'
  get  '/map',  to: 'shops#map'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  root 'shops#home'
  get  '/signup',  to: 'members#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post '/guest_login', to: 'sessions#new_guest'
  get  '/registration',  to: 'shops#new'
  resources :members
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :shops
  resources :posts,          only: [:create, :destroy]
end

app/models/shop.rb
class Shop < ApplicationRecord
  extend Geocoder::Model::ActiveRecord
  belongs_to :member
  belongs_to :latest_post, class_name: "Post", optional: true
  belongs_to :latest_img, class_name: "Post", optional: true
  has_many  :posts, dependent: :destroy
  has_many  :shop_tag_relations, dependent: :destroy
  has_many  :tags, through: :shop_tag_relations
  validates :name, presence: true, length: { maximum: 50 }
  validates :address, presence: true, length: { maximum: 100 }
  validates :opening_ours, length: { maximum: 255 }
  validates :parking, length: { maximum: 50 }
  validates :member_id, presence: true
  geocoded_by :address
  reverse_geocoded_by :latitude, :longitude
  after_validation :geocode, if: :address_changed?

  def save_tags(save_tags)
    current_tags = self.tags.nil? ? [] : self.tags.pluck(:id)
    save_tags = [] if save_tags.nil?

    old_tags = current_tags - save_tags
    new_tags = save_tags - current_tags

    # Destroy old taggings:
    old_tags.each do |old_id|
      self.tags.delete Tag.find(old_id)
    end

    # Create new taggings:
    new_tags.each do |new_id|
      post_tag = Tag.find(new_id)
      self.tags << post_tag
    end
  end

  def self.search(search)
    case search

    # 全件検索
    when "all"
      Shop.order("point_avg DESC")

    # ホーム画面用
    when "home"
      Shop.joins("INNER JOIN posts ON shops.latest_post_id = posts.id").order("posts.created_at DESC").limit(3)

    else
      # 店舗詳細ページからのリンク
      if search["shop"]
        Shop.where("id = #{search['shop']}")
      elsif search["tag_ids"]
        # タグ指定あり
        if search["AO"] == "AND"
          # AND検索
          Shop.joins(:shop_tag_relations).where("address LIKE ? AND name LIKE ? AND tag_id IN (?) ", "%#{search['area']}%", "%#{search['name']}%", search["tag_ids"])
              .group("shops.id").having("count(shops.id) = ?", search["tag_ids"].size).order("point_avg DESC")
        else
          # OR検索
          Shop.joins(:shop_tag_relations).where("address LIKE ? AND name LIKE ? AND tag_id IN (?) ", "%#{search['area']}%", "%#{search['name']}%", search["tag_ids"])
              .order("point_avg DESC")
        end
      else
        # タグ指定なし
        Shop.where("address LIKE ? AND name LIKE ? ", "%#{search['area']}%", "%#{search['name']}%").order("point_avg DESC")
      end
    end
  end

  # 店舗の平均ポイントを取得
  def self.cal_point_avg(shop)
    shop.posts.average(:point)
  end

  def self.area_conf
    area = Hash.new { |h, k| h[k] = Hash.new(&h.default_proc) }
    area["東京"][0] = %w[武蔵野 三鷹 新宿]
    area["東京"][1] = %w[吉祥寺 池袋 千代田区 国分寺]
    area["愛知"][0] = %w[名古屋 豊橋]
    area["愛知"][1] = %w[一宮 岡崎 常滑]
    area
  end

  def self.type_conf
    [[1, "/images/ramen.jpg"],
     [2, "/images/tsukemen.jpeg"],
     [3, "/images/aburasoba.jpeg"],
     [17, "/images/nibosi.jpeg"],
     [12, "/images/ziro.jpeg"]]
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :logged_in_member, only: %i[new create edit update destroy]
  before_action :admin_member,     only: :destroy

  def home
    @shops = Shop.search("home")
    @area = Shop.area_conf
    @type = Shop.type_conf
  end

  def search
    @shops = Shop.search(post_params).paginate(page: params[:page], per_page: 20)
    find_set
    @shops = Shop.search("all").paginate(page: params[:page], per_page: 20) if @shops.empty?
    @tags = Tag.name_set(params[:post][:tag_ids]) if params[:post][:tag_ids]
  end

  def map
    @shops = Shop.search(post_params)
    find_set
    @shops = Shop.search("all") if !params[:post][:shop] && @shops.empty?
    @tags = Tag.name_set(params[:post][:tag_ids]) if params[:post][:tag_ids]
  end

  def show
    @shop = Shop.find(params[:id])
    @posts = @shop.posts
    @post = Post.new
  end

  def postlist
    @shop = Shop.find(params[:id])
    @posts = @shop.posts.paginate(page: params[:page], per_page: 3)
    redirect_to @shop if @posts.empty?
    @post = Post.new
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = current_member.shops.build(shop_params)
    if @shop.save
      @shop.save_tags(params[:shop][:tag_ids])
      flash[:success] = "店舗を登録しました！"
      redirect_to shop_path(@shop.id)
    else
      render "new"
    end
  end

  def edit
    @shop = Shop.find(params[:id])
  end

  def update
    @shop = Shop.find(params[:id])
    if @shop.update(shop_params)
      @shop.save_tags(params[:shop][:tag_ids])
      flash[:success] = "店舗情報が更新されました"
      redirect_to @shop
    else
      render "edit"
    end
  end

  def destroy
    Shop.find(params[:id]).destroy
    flash[:success] = "店舗を削除しました"
    redirect_to request.referer
  end

  private

  def shop_params
    params.require(:shop).permit(:name, :address, :opening_ours, :sheets, :parking, :latitude, :longitude, tag_ids: [])
  end

  def post_params
    params.require(:post).permit(:area, :name, :AO, :shop, tag_ids: [])
  end

  # 検索結果が存在したか否かを@findにセット
  def find_set
    @find = true
    if !params[:post][:shop] && (@shops.empty? || (params[:post][:area].empty? && params[:post][:name].empty? && params[:post][:tag_ids].nil?))
      @find = false
    end
  end
end

app/views/shops/_googlemap.html.erb
<script>
  if(window.google){
    initMap();
  } else{
    $.ajax('https://maps.googleapis.com/maps/api/js?key=AIzaSyDzZIPZF0Uch20mSuje8gzNVh2MYViAHlM&callback=initMap', {
      crossDomain: true,
      dataType: 'script'
    });
  }
</script>

app/views/shops/_modalSession.html.erb
<div class="modal js_modal modal_session_edit modal_session_post">
  <div class="modal__bg js_modal_close"></div>
    <div class="modal__content">
      <%= render partial: "sessions/session" %>
    </div>
  </div>
</div>

app/views/shops/_result.html.erb
<div class="result">
  <% if @find %>
    <div class="result_area">
      <%= params['post']['area'] %>
    </div>
    <div class="result_name">
      <%= params['post']['name'] %>
    </div>
    <div class="result_shop">
      <%= params['post']['shop_name'] %>
    </div>
    <div class="result_tag">
      <% if @tags %>
        <% @tags.each do |tag| %>
          <%= tag %>
        <% end %>
      <% end %>
      <% if params['post']['tag_ids'] %>
        <%= params['post']['AO'] == 'AND' ? '(選択した全てのタグを含む(AND))' : '(選択した一部のタグを含む(OR))' %>
      <% end %>
    </div>
  <% else %>
    <div class="result_all">
      全国のお店
    </div>
    <div class="result_notes">
      ※ご指定の条件ではお店が見つかりませんでした。
    </div>
  <% end %>
</div>

app/views/shops/_shop.html.erb
<% if controller.action_name == "search" %>
  <div class="shop_search">
<% else %>
  <div class="shop_map">
<% end %>

  <%= link_to "", shop, class: :wrap %>
  <div class="shop_left">
    <div class="shop_image">
        <div class="liquid">
          <% if shop.latest_img %>
              <%= image_tag(shop.latest_img.images.first) %>
          <% else %>
            <img src="/images/no_image.png" alt="NoImage" />
          <% end %>
        </div>
    </div>
  </div>
  <div class="shop_right">
    <div class="shop_right_name">
      <%= shop.name %>
    </div>
    <div class="shop_right_address">
      <%= shop.address %>
    </div>
    <div class="shop_right_point">
      <div class="shop_right_point_raty">
        <div class="raty" read_only="true" data_score="<%= shop.point_avg %>"></div>
      </div>
      <div class="shop_right_point_num">
        <%= shop.point_avg || "未評価" %>
      </div>
      <% if shop.posts.count > 0 %>
        <div class="shop_head_point_review">
          <span class="review_icon">レビュー</span>
          <%= "#{shop.posts.count}件" %>
        </div>
      <% end %>
    </div>
    <div class="shop_right_tags">
      <div class="tags">
        <% shop.tags.each do |tag| %>
          <span class="tag">
            <%= tag.name %>
          </span>
        <% end %>
      </div>
    </div>
    <% if controller.action_name == "search" %>
      <div class="shop_right_topCom">
        <div class="shop_right_topCom_title">
          <% if shop.latest_post %>
            <%= shop.latest_post.title %>
            <span class="shop_right_topCom_title_by">
              by <%= link_to shop.latest_post.member.name, postlist_member_path(shop.latest_post.member) %> さん
            </span>
            <div class="shop_right_topCom_comment">
              <%= shop.latest_post.comment %>
            </div>
          <% else %>
            ※まだレビューがありません
          <% end %>
        </div>
      </div>
    <% else %>
      <%= shop.posts.count %>件のレビュー
    <% end %>
  </div>
</div>
    <% if current_member && current_member.admin? %>
      <div class="shop_right_delete">
        <%= link_to "この店舗を削除", shop, method: :delete,data: { confirm: "削除しますか？" } %>
      </div>
    <% end %>

app/views/shops/_shopHead.html.erb
<div class="shop_head">
  <div class="shop_head_left">
    <div class="shop_head_name">
      <%= controller.action_name == "show" ? @shop.name : link_to(@shop.name, shop_path(@shop)) %>
    </div>
    <div class="shop_head_point">
      <div class="raty" read_only="true" data_score="<%= @shop.point_avg %>"></div>
      <div class="shop_head_point_num">
        <%= @shop.point_avg || "未評価" %>
      </div>
      <% if @shop.posts.count > 0 %>
        <div class="shop_head_point_review">
          <span class="review_icon">レビュー</span>
          <%= link_to "#{@shop.posts.count}件", postlist_path(@shop) %>
        </div>
      <% end %>
    </div>
    <div class="shop_head_tag">
      <div class="tags">
        <% @shop.tags.each do |tag| %>
          <span class="tag">
            <%= tag.name %>
          </span>
        <% end %>
      </div>
    </div>
  </div>
  <div class="shop_head_right">
    <% if current_member %>
      <%= link_to "店舗情報編集", edit_shop_path(@shop), class: "btn_flat shop_edit_btn"%>
      <%= link_to "レビューを投稿する", "", class: "js_modal_open btn_flat post_create_btn", id: :modal_post %>
    <% else %>
      <%= link_to "店舗情報編集", edit_shop_path(@shop), class: "js_modal_open btn_flat shop_edit_btn", id: :modal_session_edit %>
      <%= link_to "レビューを投稿する", "", class: "js_modal_open btn_flat post_create_btn", id: :modal_session_post %>
    <% end %>
  </div>
</div>

<%= render partial: "posts/postform" %>
<%= render partial: "shops/modalSession" %>

app/views/shops/edit.html.erb
<% provide(:title, '店舗情報更新') %>
<% breadcrumb :edit_shop, @shop %>
<h1>店舗情報の更新</h1>
<%= render partial: "shopform" %>

app/views/shops/home.html.erb
<script>
$(document).on('turbolinks:load', function(){
  //続きを読む機能
  $('.home_left_review_shop_right_name').each(function(e){
    let $comment = $(this);
    // 元の文章を変数に格納
    let comment = $comment.html();
    let commentShow;
    let commentText;
    if($comment.height() > 40){
      // 文章の要素の高さが20を超えていたら隠す用のisHiddenクラスを付与
      $comment.addClass('isHidden');
      commentShow = comment.replace(/<br>/g, "\u00a0").substring(0, 35);
      commentText = commentShow += '...';
      $comment.html(commentText);
    }
  });
});
</script>
<div class="home">
  <div class="home_left">

    <div class="caption_home">
      最近レビューが投稿されたお店
    </div>
    <div class="home_left_review">
      <% @shops.each do |shop| %>
        <div class="home_left_review_shop">
          <%= link_to "", shop, class: :wrap %>
          <div class="home_left_review_shop_left">
            <div class="home_left_review_shop_left_img">
              <div class="liquid">
                <% if shop.latest_img %>
                  <%= image_tag(shop.latest_img.images.first) %>
                <% else %>
                  <%= image_tag("/images/no_image.png") %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="home_left_review_shop_right">
            <div class="home_left_review_shop_right_name">
              <%= shop.name %>
            </div>
            <div class="home_left_review_shop_right_point">
              <div class="home_left_review_shop_right_point_raty">
                <div class="raty" read_only="true" data_score="<%= shop.point_avg %>"></div>
              </div>
              <div class="home_left_review_shop_right_point_num">
                <%= shop.point_avg || "未評価" %>
              </div>
              <% if shop.posts.count > 0 %>
                <div class="home_left_review_shop_right_point_review">
                  <span class="review_icon">レビュー</span>
                  <%= "#{shop.posts.count}件" %>
                </div>
              <% end %>
            </div>
            <div class="home_left_review_shop_right_tags">
              <div class="tags">
                <% shop.tags.first(2).each do |tag| %>
                  <span class="tag">
                    <%= tag.name %>
                  </span>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="caption_home">
      エリアから探す
    </div>
    <div class="home_left_area">
      <% @area.each do |prefecture| %>
        <div class="home_left_area_prefecture">
          <div class="prefecture">
            <%= prefecture[0] %>
            <span class="prefecture_count">(<%= Shop.where("address LIKE ?","%#{prefecture[0]}%").count %>件)</span>
          </div>
          <div class="home_left_area_many">
            <% prefecture[1][0].each do |area| %>
              <div class="home_left_area_many_item">
                <a href="<%= search_path(@shop, params: { post: { area: "#{area}", name: ""} }) %>">
                  <%= area %>
                  <span class='count'>(<%= Shop.where("address LIKE ?","%#{area}%").count %>件)</span>
                </a>
              </div>
            <% end %>
          </div>
          <ul class="home_left_area_few">
            <% prefecture[1][1].each do |area| %>
              <li class="home_left_area_few_item">
                <%= link_to( "#{area}",search_path(@shop, params: { post: { area: "#{area}", name: ""} })) %>
              </li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
    
    <div class="caption_home">
      こだわり条件から探す
    </div>
    <div class="home_left_type">
      <div class="home_left_type_mamy">
        <% @type.each do |t| %>
          <div class="home_left_type_mamy_item">
            <%= link_to('' ,search_path(@shop, params: { post: { area: "", name: "", tag_ids: [t[0]] }}), class: :wrap) %>
            <img src="<%= t[1] %>",alt="<%= Tag.find(t[0]).name %>") />
            <span>
              <%= Tag.find(t[0]).name %><br />
              <p class="tag_count"><%= Shop.joins(:shop_tag_relations).where("tag_id = ?", t[0]).count %>件</p>
            </span>
          </div>
        <% end %>
      </div>
      <div class="home_left_type_few">
        <% Tag.all.each do |t| %>
          <% match = false %>
          <% @type.each do |tp| %>
            <% if t.id == tp[0] %>
              <% match = true %>
              <% break %>
            <% end %>
          <% end %>
          <% next if match %>
          <div class="home_left_type_few_tag">
            <%= link_to(t.name ,search_path(@shop, params: { post: { area: "", name: "", tag_ids: [t] }})) %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="home_right">
    <div class="home_right_count">
      <div class="home_right_count_shops">
        <div class="home_right_count_shops_num">
          <%= Shop.count %> 
        </div>
        <div class="home_right_count_shops_name">
          店舗
        </div>
      </div>
      <div class="home_right_count_posts">
        <div class="home_right_count_posts_num">
          <%= Post.count %>
        </div>
        <div class="home_right_count_posts_name">
          レビュー
        </div>
      </div>
    </div>
    <% if logged_in? %>
      <div class="home_right_profile">
        <div class="home_right_profile_head">
          <%= link_to "", postlist_member_path(current_member), class: :wrap %>
          <div class="home_right_profile_head_icon">
            <div class="liquid">
              <%= current_member.image.attached? ? image_tag(current_member.image) : image_tag("/images/default_member.png")  %>
            </div>
          </div>
          <span class="home_right_profile_head_name">
            <%= current_member.name %> さん
          </span>
        </div>
        <div class="home_right_profile_posts">
          <div class="home_right_profile_posts_name">
            レビュー投稿数
          </div>
          <div class="div_right">
            <%= current_member.posts.count %>
          </div>
        </div>
        <div class="home_right_profile_shops">
          <div class="home_right_profile_shops_name">
            店舗登録数
          </div>
          <div class="div_right">
            <%= current_member.shops.count %>
          </div>
        </div>
      </div>
    <% else %>
      <%= render partial: "sessions/session" %>
    <% end %>
  </div>
</div>

app/views/shops/new.html.erb
<% provide(:title, '新規店舗登録') %>
<% breadcrumb :registration %>
<h1>新規店舗登録</h1>
<%= render partial: "shopform" %>

app/views/shops/postlist.html.erb
<% provide(:title, @shop.name) %>
<% breadcrumb :postlist, @shop %>

<div class="row">
      
  <%= render partial: "shopHead" %>

  <div class="caption_postList">
    レビュー一覧
  </div>   

<%= will_paginate @posts %>
   
  <ul>
    <% @posts.each do |post| %>
      <li class="postList" id=<%= "post#{post.id}" %>>
        <div class="postList_member">
          <div class="postList_member_left">
            <div class="postList_member_left_memberImg">
              <div class="liquid">
                <%= link_to( post.member.image.attached? ? image_tag(post.member.image) : image_tag("/images/default_member.png"), postlist_member_path(post.member))  %>
              </div>
            </div>
          </div>
          <div class="postList_member_right">
            <div class="postList_member_right_name">
              <%= link_to(post.member.name, postlist_member_path(post.member)) %>
              さんのレビュー
            </div>
            <div class="postList_member_right_dtl">
              <div class="postList_member_right_dtl_raty">
                <div class="raty" read_only="true" data_score="<%= post.point %>"></div>
                <div class="postList_member_right_dtl_raty_num">
                  <%= post.point %>
                </div>
              </div>
              <div class="postList_member_right_dtl_date">
                <%= "投稿日:#{post.created_at.strftime('%Y/%m/%d')}" %>
              </div>
            </div>
          </div>
        </div>
        <div class="postList_content">
          <div class="postList_content_title">
            <%= post.title %>
          </div>
          <div class="postList_content_comment">
            <%= simple_format(post.comment) %>
          </div>
          <div class="postList_content_images">
          <% if post.images.attached? %>
            <% post.images.each do |image| %>
              <div class="postList_content_images_img">
                <a class="js_modal_open" id="<%= "modal_image_#{image.id}" %>" href="">
                  <div class="liquid">
                    <%= image_tag image %>
                  </div>
                </a>
              </div>
              <div class="modal js_modal <%= "modal_image_#{image.id}" %>">
                <div class="modal__bg js_modal_close"></div>
                <div class="modal__content_img">
                  <%= image_tag image %>
                </div>
              </div>
            <% end %>
          <% end %>
          </div>
          <% if current_member && ( current_member?(post.member) || current_member.admin? ) %>
            <div class="postList_content_delete right">
              <%= link_to "このレビューを削除", post, method: :delete,data: { confirm: "削除しますか？" } %>
            </div>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>

<%= will_paginate @posts %>

</div>

app/views/shops/search.html.erb
<script>
$(document).on('turbolinks:load', function(){
  //続きを読む機能
  $('.shop_right_topCom_comment').each(function(e){
    let $comment = $(this);
    // 元の文章を変数に格納
    let comment = $comment.html();
    let commentShow;
    let commentText;
    if($comment.height() > 20){
      // 文章の要素の高さが20を超えていたら隠す用のisHiddenクラスを付与
      $comment.addClass('isHidden');
      commentShow = comment.replace(/<br>/g, "\u00a0").substring(0, 70);
      commentText = commentShow += '......';
      $comment.html(commentText);
    }
  });
});
</script>

<% provide(:title, '店舗検索') %>
<% breadcrumb :search %>
<%= render partial: "result" %>
<%= @result %>

<%= will_paginate %>

<ul class="shops">
  <%= render @shops %>
</ul>

<%= will_paginate %>

app/views/shops/show.html.erb
<% provide(:title, @shop.name) %>
<% breadcrumb :shops_show, @shop %>

<script>
  $(window).on('load',function(){
    $('.postform_point input[name="score"]').val(0);
  });
  $(document).on('turbolinks:load', function(){
    //続きを読む機能
    $('.shop_Com_right_comment').each(function(e){
      let $comment = $(this);
      // 元の文章を変数に格納
      let comment = $comment.html();
      let commentShow;
      let commentText;
      if($comment.height() > 70){
        // 文章の要素の高さが70を超えていたら隠す用のisHiddenクラスを付与
        $comment.addClass('isHidden');
        commentShow = comment.replace(/<br>/g, "\u00a0").substring(0, 128);
        commentText = commentShow += '...続きを読む';
        $comment.html(commentText);
      }
    });
  });
  function initMap(){

    // マーカー用のデータを取得
    const shopdata = [
      <% if @shop.latitude && @shop.longitude %>
        <%= "{ lat: #{@shop.latitude}, lng: #{@shop.longitude} }".html_safe %>
      <% end %>
    ];
    
    let map;
    map = new google.maps.Map(document.getElementById('map'), {
      maxZoom: 19,
      zoom: 15,
      scrollwheel: false,
      disableDefaultUI: true,
    });
    shopdata.map(d => {
      // マーカーをつける
      const marker = new google.maps.Marker({
        position: {lat: parseFloat(d.lat), lng: parseFloat(d.lng)},
        map: map,
        icon: {
            url: '/images/marker.png',
            scaledSize : new google.maps.Size(40, 38)
        }
      });
    });

    //マーカーがいい感じに表示できるよう調整
    map.fitBounds(new google.maps.LatLngBounds(
      //sw
      {
        lat: Math.min(...shopdata.map(d => d.lat)),
        lng: Math.min(...shopdata.map(d => d.lng))
      },
      //ne
      {
        lat: Math.max(...shopdata.map(d => d.lat)),
        lng: Math.max(...shopdata.map(d => d.lng))
      }
    ));
  }
</script>

<%= render partial: "googlemap" %>

<div class="other">
      
  <%= render partial: "shopHead" %>


    <div class="shop_dtl_right">
      <% @no_image = true %>
      <% @image_cnt = 0 %>
      <% @posts.each do |post| %>
        <% if post.images.attached? %>
          <% post.images.each do |image| %>
            <div class="shop_dtl_right_img">
              <a class="js_modal_open" id="<%= "modal_image_#{image.id}" %>" href="">
                <div class="liquid">
                  <%= image_tag image %>
                </div>
              </a>
            </div>
            <div class="modal js_modal <%= "modal_image_#{image.id}" %>">
              <div class="modal__bg js_modal_close" id="<%= "modal_image_#{image.id}" %>"></div>
              <div class="modal__content_img">
                  <%= image_tag image %>
              </div>
            </div>
            <% @image_cnt +=1 %>
            <% break if @image_cnt > 9 %>
          <% end %>
          <% @no_image = false %>
        <% end %>
        <% break if @image_cnt > 9 %>
      <% end %>
    </div>

    <div class="caption_shop">
      レビュー
    </div>   
  <% if @posts.empty? %>
      ※まだレビューがありません。
  <% else %>
    <ul>
      <% @posts.first(3).each do |post| %>
        <li class="shop_Com">
          <div class="shop_Com_left">
            <%= link_to "", postlist_member_path(post.member), class: :wrap %>
            <div class="shop_Com_left_memberImg">
              <div class="liquid">
                <%= post.member.image.attached? ? image_tag(post.member.image) : image_tag("/images/default_member.png") %>
              </div>
            </div>
            <div class="shop_Com_left_memberName">
              <%= post.member.name %>
            </div>
          </div>
          <div class="shop_Com_right">
            <%= link_to "", "/postlist/#{@shop.id}#post#{post.id}", class: :wrap %>
            <div class="shop_Com_right_title">
                <%= post.title %>
            </div>
            <div class="shop_Com_right_comment" id=<%= post.id %>>
              <%= simple_format(post.comment) %>
            </div>
            <div class="shop_Com_right_dtl">
              <div class="shop_Com_right_dtl_raty">
                <div class="raty" read_only="true" data_score="<%= post.point %>"></div>
              </div>
              <div class="shop_Com_right_dtl_date">
                <%= "投稿日:#{post.created_at.strftime('%Y/%m/%d')}" %>
              </div>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
    <div class="right">
      <%= link_to "レビューをすべて読む(#{@posts.count}件)", postlist_path(@shop) %>
    </div>
  <% end %>

    <div class="caption_shop">
      店舗詳細
    </div>   
    <div class="shop_dtl_left">
      <table class="table">
        <tr>
          <th>店名</th>
          <td><%= @shop.name %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td>
            <div class="address_map">
              <a href="<%= map_path(@shop, params: { post: { shop: @shop, shop_name: @shop.name }}) %>" class="wrap">
                <%= @shop.address %>
                <!-- 地図を操作させない -->
                <div class="map_wrapper"></div>
                <div id='map' class="shop_dtl_left_map"></div>
              </a>
            </div>
          </td>
        </tr>
        <tr>
          <th>営業時間</th>
          <td><%= simple_format(@shop.opening_ours) %></td>
        </tr>
        <tr>
          <th>席数</th>
          <td><%= @shop.sheets %></td>
        </tr>
        <tr>
          <th>駐車場</th>
          <td><%= @shop.parking %></td>
        </tr>
        <tr>
          <th>店舗登録者</th>
          <td><%= link_to @shop.member.name, postlist_member_path(@shop.member) %></td>
        </tr>
      </table>
    </div>
</div>