config/routes.rb
Rails.application.routes.draw do
  get  '/search',  to: 'shops#search'
  get  '/postlist/:id',  to: 'shops#postlist', as: 'postlist'
  get  '/postlist_member/:id',  to: 'members#postlist_member', as: 'postlist_member'
  get  '/map',  to: 'shops#map'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  root 'shops#home'
  get  '/signup',  to: 'members#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post '/guest_login', to: 'sessions#new_guest'
  get  '/registration',  to: 'shops#new'
  resources :members
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :shops
  resources :posts,          only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  Copyright (c) menbiyori.com, Inc. All Rights Reserved. 
</footer>

app/views/layouts/_header.html.erb
<script>
  $(function(){
    $('.js_switch').on('click',function(){
        $('.search_form_hide').slideToggle(200);
        return false;
    });
  });
(function () {
 
  // 「一覧表示」ボタン押下時
  var btnList_onclick = function (event) {
    $("#search_form_id").attr("action", "<%= search_path %>").submit();
  };

  // 「地図表示」ボタン押下時
  var btnMap_onclick = function (event) {
    $("#search_form_id").attr("action", "<%= map_path %>").submit();
  };
 
  // ドキュメント読み込み完了時
  var document_onready = function (event) {
    $("#btn_list").on("click", btnList_onclick).focus();
    $("#btn_map").on("click", btnMap_onclick);
  };
 
  $(document).ready(document_onready);
})();
</script>

<header>
  <div class="header_contents">
    <div class="global_search">
      <div class="global_search_title">
        <%= link_to( image_tag("/images/logo.png") , root_path, id: "logo") %>
      </div>
      <div class="global_search_form">
        <%= form_with(url: "", local: true, id: "search_form_id", method: "get") do |f| %>
          <div class='search_form'>
            <div class='search_form_word'>
              <div class='search_form_word_area'>
                <%= f.text_field 'post[area]', placeholder: 'エリア[例:池袋、新宿]', class: 'form-control' %>
              </div>
              <div class='search_form_word_name'>
                <%= f.text_field 'post[name]', placeholder: '店名', class: 'form-control' %>
              </div>
            <div class='search_form_switch'>
              <a class='js_switch btn_flat search_dtl_btn'>＋こだわり条件</a>
            </div>
              <div class='search_form_btn'>
                <%= f.submit '一覧検索', class: "btn list_btn", id: "btn_list" %>
              </div>
              <div class='search_form_btn_map'>
                <%= f.submit '地図検索', class: "btn map_btn", id: "btn_map" %>
              </div>
            </div>
            <div class='search_form_hide'>
              <div class='search_form_AO'>
                <%= f.select 'post[AO]', {'選択した全てのタグを含む(AND)': 'AND', '選択した一部のタグを含む(OR)': 'OR'}, {selected: 'AND'} %>
              </div> 
                <%= render partial: 'shared/tagsform', locals: { obj: f, name: "post[tag_ids]" } %>
            </div> 
          </div>
        <% end %>
      </div>
    </div>
    <ul class="navigation">
      <% if logged_in? %>
        <li><%= link_to "店舗登録", registration_path %></li>
        <li><%= link_to "会員一覧", members_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <div class="navigation_icon">
              <div class="liquid">
                <%= current_member.image.attached? ? image_tag(current_member.image) : image_tag("/images/default_member.png")  %>
              </div>
              <div><b class="caret"></b></div>
            </div>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "プロフィール", postlist_member_path(current_member) %></li>
            <% if current_member.email != "guest@example.com" %>
              <li><%= link_to "設定", edit_member_path(current_member) %></li>
            <% end %>
            <li class="divider"></li>
            <li>
              <%= link_to "ログアウト", logout_path, method: :delete %>
            </li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "ログイン", login_path %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('/images/favicon.ico') %>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.2/dist/jquery.validate.min.js"></script>

    <%= render 'layouts/shim' %>
  </head>
  <body>
  <input type="hidden" id="refresh" value="no">
    <%= render 'layouts/header' %>

    <% if controller.action_name == "home" %>
      <div id="home" class="home_contents">
    <% else %>
      <div id="other" class="other_contents">
      <span class="bread_home">ホーム</span>
      <%= breadcrumbs separator: " &rsaquo; " %>
    <% end %>

      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>

      <%= debug(params) if Rails.env.development? %>
       
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>